name: github-UBI8-NIGHTLY

# Runs every night at midnight
on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubi8-nightly:
    name: ubi8-nightly
    runs-on: [opencsp-latest-ubi8-latest]
    permissions:
      packages: read
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: OpenCSP

      - name: pytest-cov
        working-directory: OpenCSP/example
        run: |
          python3 -m pip install -r ../requirements.txt
          export PYTHONPATH=$PWD/../
          pytest --color=yes -rs -vv --cov=. --cov-report term --cov-config=.coveragerc

      - name: Pip Upgrade pytest-cov
        working-directory: OpenCSP/example
        run: |
          python3 -m pip install -U -r ../requirements.txt
          export PYTHONPATH=$PWD/../
          pytest --color=yes -rs -vv --cov=. --cov-report term --cov-config=.coveragerc