name: github-UBI8

on:
  pull_request:
    paths-ignore:
    - '**/*.rst'
    - '**/*.md'
    - 'doc/**'
    types: [ opened, reopened, synchronize ]

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubi8-ci:
    name: ubi8-ci
    runs-on: [ubuntu-latest]
    permissions:
      packages: read
      contents: read
    container: 
      image: ghcr.io/sandialabs/opencsp:latest-ubi8
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: OpenCSP

      - name: pytest-cov
        working-directory: OpenCSP/opencsp
        run: |
          python3 -m pip install -r ../requirements.txt
          export PYTHONPATH=$PWD/../
          pytest --color=yes -rs -vv --cov=. --cov-report term --cov-config=.coveragerc